.nh
.TH "NOSTROMO-RENAME-CMD" "1" "Oct 2023" "nostromo 0.12.0" "nostromo manual"

.SH NAME
.PP
nostromo-rename-cmd - Rename a command in nostromo manifest


.SH SYNOPSIS
.PP
\fBnostromo rename cmd [key.path] [name] [options] [flags]\fP


.SH DESCRIPTION
.PP
Rename a command in nostromo manifest for a given key path.
A key path is a '.' delimited string, e.g., "key.path" which represents
the alias which can be run as "key path" for the actual command provided.

.PP
Manipulate the core nostromo manifest by renaming command nodes.
Using rename, take a source key path and rename it to a new name with
all subcommands in tow.

.PP
If the new name already exists, the command will fail.

.PP
Optionally provide a description with -d to the destination.


.SH OPTIONS
.PP
\fB-d\fP, \fB--description\fP=""
	Description of the command to rename

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for cmd


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show verbose logging


.SH SEE ALSO
.PP
\fBnostromo-rename(1)\fP
