.nh
.TH "NOSTROMO-RENAME" "1" "Oct 2023" "nostromo 0.12.0" "nostromo manual"

.SH NAME
.PP
nostromo-rename - Rename a command in nostromo manifest


.SH SYNOPSIS
.PP
\fBnostromo rename [flags]\fP


.SH DESCRIPTION
.PP
Rename a command in nostromo manifest


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for rename


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show verbose logging


.SH SEE ALSO
.PP
\fBnostromo(1)\fP, \fBnostromo-rename-cmd(1)\fP
