.nh
.TH "NOSTROMO-FIND" "1" "Oct 2023" "nostromo 0.12.0" "nostromo manual"

.SH NAME
.PP
nostromo-find - Find matching commands and substitutions


.SH SYNOPSIS
.PP
\fBnostromo find [name] [flags]\fP


.SH DESCRIPTION
.PP
Find matching commands and substitutions in nostromo.

.PP
Searches for "name" in commands and substitutions and prints matches.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for find


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show verbose logging


.SH SEE ALSO
.PP
\fBnostromo(1)\fP
