.nh
.TH "NOSTROMO-GET" "1" "Oct 2023" "nostromo 0.12.0" "nostromo manual"

.SH NAME
.PP
nostromo-get - Get a config item from manifest


.SH SYNOPSIS
.PP
\fBnostromo get [key] [flags]\fP


.SH DESCRIPTION
.PP
Get a config item from manifest.
Nostromo config items are saved in the manifest.

.PP
Use this command to get keys to examine these settings:
verbose: boolean
aliasesOnly: boolean
backupCount: number


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for get


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show verbose logging


.SH SEE ALSO
.PP
\fBnostromo(1)\fP
