.nh
.TH "NOSTROMO-INIT" "1" "Oct 2023" "nostromo 0.12.0" "nostromo manual"

.SH NAME
.PP
nostromo-init - Initialize nostromo configuration


.SH SYNOPSIS
.PP
\fBnostromo init [flags]\fP


.SH DESCRIPTION
.PP
Create a nostromo config file with defaults.

.PP
By default the config file is located at ~/.nostromo/ships/manifest.yaml.

.PP
Customize this with the $NOSTROMO_HOME environment variable


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for init


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-v\fP, \fB--verbose\fP[=false]
	show verbose logging


.SH SEE ALSO
.PP
\fBnostromo(1)\fP
